server:
  port: 8080
  name: springboot3-ztoany-starter-sample
  shutdown: graceful
  tomcat:
    accesslog:
      directory: D:\tmp\springlog

spring:
  application:
    name: springboot3-ztoany-starter-sample
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 12345
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create

logging:
  file:
    path: D:\tmp\springlog
