server:
  port: 8080
  name: springboot3-elide-sample
  shutdown: graceful

spring:
  application:
    name: springboot3-elide-sample
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 12345
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create

elide:
  json-api:
    path: /api
    enabled: true
  graphql:
    path: /graphql/api
    enabled: true
  api-docs:
    path: /doc
    enabled: true
    version: openapi_3_0

